import { PropertyHomesData } from "@/types/propertyHomesData";
import { PropertyHomes } from "@/types/properyHomes";

const propertyHomesData: PropertyHomesData[] = [
  {
    name: "Serenity height villas",
    slug: "serenity-height-villas",
    location: "15 s aurora ave, miami",
    rate: "570,000",
    beds: 4,
    baths: 3,
    area: 120,
    images: [
      "/images/properties/property1/property1.jpg",
      "/images/properties/property1/image-2.jpg",
      "/images/properties/property1/image-3.jpg",
      "/images/properties/property1/image-4.jpg",
    ],
  },
  {
    name: "Mountain retreat villa",
    slug: "mountain-retreat-villa",
    location: "18 s aurora ave, miami",
    rate: "575,000",
    beds: 5,
    baths: 2,
    area: 150,
    images: [
      "/images/properties/property2/property2.jpg",
      "/images/properties/property2/image-2.jpg",
      "/images/properties/property2/image-3.jpg",
      "/images/properties/property2/image-4.jpg",
    ],
  },
  {
    name: "Modern luxe villa",
    slug: "modern-luxe-villa",
    location: "20 s aurora ave, miami",
    rate: "580,000",
    beds: 3,
    baths: 4,
    area: 180,
    images: [
      "/images/properties/property3/property3.jpg",
      "/images/properties/property3/image-2.jpg",
      "/images/properties/property3/image-3.jpg",
      "/images/properties/property3/image-4.jpg",
    ],
  },
  {
    name: "Royal orchid villas",
    slug: "royal-orchid-villas",
    location: "12 emerald heights, los angeles",
    rate: "590,000",
    beds: 6,
    baths: 3,
    area: 200,
    images: [
      "/images/properties/property4/property4.jpg",
      "/images/properties/property4/image-2.jpg",
      "/images/properties/property4/image-3.jpg",
      "/images/properties/property4/image-4.jpg",
    ],
  },
  {
    name: "Grand vista villas",
    slug: "grand-cista-villas",
    location: "25 skyline boulevard, san diego",
    rate: "710,000",
    beds: 2,
    baths: 1,
    area: 90,
    images: [
      "/images/properties/property5/property5.jpg",
      "/images/properties/property5/image-2.jpg",
      "/images/properties/property5/image-3.jpg",
      "/images/properties/property5/image-4.jpg",
    ],
  },
  {
    name: "Imperial pearl villas",
    slug: "imperial-pearn-villas",
    location: "18 sapphire bay road, naples",
    rate: "630,000",
    beds: 4,
    baths: 2,
    area: 130,
    images: [
      "/images/properties/property6/property6.jpg",
      "/images/properties/property6/image-2.jpg",
      "/images/properties/property6/image-3.jpg",
      "/images/properties/property6/image-4.jpg",
    ],
  },
  {
    name: "Opulent haven villas",
    slug: "opulent-heven-villas",
    location: "22 ocean breeze drive, malibu",
    rate: "620,000",
    beds: 6,
    baths: 3,
    area: 180,
    images: [
      "/images/properties/property7.jpg",
      "/images/properties/property9.jpg",
      "/images/properties/property2.jpg",
      "/images/properties/property5.jpg",
    ],
  },
  {
    name: "Elite crest villas",
    slug: "elite-crest-villas",
    location: "10 palm view lane, beverly hills",
    rate: "750,000",
    beds: 4,
    baths: 3,
    area: 150,
    images: [
      "/images/properties/property8.jpg",
      "/images/properties/property2.jpg",
      "/images/properties/property4.jpg",
      "/images/properties/property7.jpg",
    ],
  },
  {
    name: "Majestic bay villas",
    slug: "majestic-bay-villas",
    location: "8 sunset cove, miami beach",
    rate: "680,000",
    beds: 4,
    baths: 2,
    area: 120,
    images: [
      "/images/properties/property9.jpg",
      "/images/properties/property3.jpg",
      "/images/properties/property5.jpg",
      "/images/properties/property9.jpg",
    ],
  },
];

// Adapter function to convert PropertyHomesData to PropertyHomes format
export const propertyHomes: PropertyHomes[] = propertyHomesData.map(
  (item, index) => ({
    id: (index + 1).toString(),
    name_ar: item.name,
    name_en: item.name,
    operation: "sale",
    type: "villa",
    bedrooms: item.beds,
    bathrooms: item.baths,
    area: item.area,
    price: parseInt(item.rate.replace(/,/g, "")),
    address_ar: item.location,
    address_en: item.location,
    details_ar: `Beautiful ${item.name} with ${item.beds} bedrooms and ${item.baths} bathrooms`,
    details_en: `Beautiful ${item.name} with ${item.beds} bedrooms and ${item.baths} bathrooms`,
    map_url: "",
    images: item.images,
    created_at: new Date().toISOString(),
  })
);
