import type { Metadata } from "next";
import { Bricolage_Grotesque, Noto_Kufi_Arabic } from "next/font/google";
import "@/app/globals.css";
import Header from "@/components/Layout/Header";
import Footer from "@/components/Layout/Footer";
import { ThemeProvider } from "next-themes";
import NextTopLoader from "nextjs-toploader";
import SessionProviderComp from "@/components/nextauth/SessionProvider";
import { NextIntlClientProvider } from "next-intl";
import { notFound } from "next/navigation";
import QueryProvider from "@/components/utils/QueryProvider";
import { Session } from "next-auth";

const englishFont = Bricolage_Grotesque({ subsets: ["latin"] });
const arabicFont = Noto_Kufi_Arabic({ subsets: ["arabic"] });

export const metadata: Metadata = {
  title: "الأندلسية للعقارات ",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  session,
  params,
}: Readonly<{
  children: React.ReactNode;
  session?: Session | null;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;
  const messages = (await import(`../../../messages/${locale}.json`)).default;
  if (!messages) return notFound();

  // Determine direction based on locale
  const dir = locale === "ar" ? "rtl" : "ltr";

  return (
    <html lang={locale} dir={dir}>
      <body
        className={`${
          locale === "ar" ? arabicFont.className : englishFont.className
        } bg-white dark:bg-black antialiased`}
      >
        <QueryProvider>
          <NextTopLoader color="#07be8a" />
          <SessionProviderComp session={session ?? null}>
            <ThemeProvider
              attribute="class"
              enableSystem={false}
              defaultTheme="light"
            >
              <NextIntlClientProvider locale={locale} messages={messages}>
                <Header />
                {children}
                <Footer />
              </NextIntlClientProvider>
            </ThemeProvider>
          </SessionProviderComp>
        </QueryProvider>
      </body>
    </html>
  );
}
